name: Workflow depenant

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: tâche 1
        run: echo "tache 1 faite"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: tâche 2
        run: echo "tache 2 faite après la première"
