name: learn-github-actions

on: 
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "C'est un push"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "C'est manuel"
          fi
